### ISSUE TITLE
Flint paper link doesn't work

### ISSUE THREAD

**Issue by panpan2** [flintlang/flint#426]
The link for the academic paper in the [README.md](https://github.com/flintlang/flint/blob/master/README.md) doesn't work (line 11).

[https://www.doc.ic.ac.uk/~fs2014/flint.pdf](https://www.doc.ic.ac.uk/~fs2014/flint.pdf) redirects to the department website possibly because [https://www.doc.ic.ac.uk/~fs2014](https://www.doc.ic.ac.uk/~fs2014) doesn't exist anymore.

**Comment by SusanEisenbach** [comment]
Thanks for this. I corrected it when I read your email.

Susan

--
Professor Susan Eisenbach
Department of Computing
Imperial College London

On 21 Feb 2019, at 12:44, Panayiotis Panayiotou <notifications@github.com<mailto:notifications@github.com>> wrote:


The link for the academic paper in the README.md<https://github.com/flintlang/flint/blob/master/README.md> doesn't work (line 11).

https://www.doc.ic.ac.uk/~fs2014/flint.pdf redirects to the department website possibly because https://www.doc.ic.ac.uk/~fs2014 doesn't exist anymore.
