### ISSUE TITLE
Unable to construct struct without declaring outer function as `mutates(...)`

### ISSUE THREAD

**Issue by mrRachar** [flintlang/flint#436]
Right now I cannot simply initialise a struct in any function, in a contract's initialiser, or in its declaration. This includes built in structs such as `Wei`. The verifier complains that to initialise these we'd need to declare the function mutating. This is strange as the idea behind `mutates(...)` is that it declares that the function mutates its struct, not just creates new values. This right now means that _every single field_ of _every single struct_ that is initialised, even if temporarily and not affecting the outer state at all, needs to be listed in the mutates list, which can get out of hand easily. Also note, `Wei.rawValue` shouldn't be read as a change in state of the blockchain, instead it is a local change of the field inside the Wei struct, and this would be needed to be done for any struct.

_Simple example_
```swift
contract Wallet {
  let coin: Wei = Wei(0)
}

Wallet :: (any) {
  public init() {} // fix with: mutates (Wei.rawValue)
}
```

_More sophisticated example_
```swift
struct Counter {
  var count: Int
  var myThing: Int = 0

  public init(value: Int = 0) {
    self.count = 0
  }
}

contract Test {
  var counter: Counter
  var owner: Address
}

Test :: caller <- (any) {
  public init() { // fix with: mutates (Counter.count, Counter.myThing)
    self.counter = Counter(4)
    self.owner = caller
    self.counter = Counter(4)
  }

  public func myFunc() { // fix with: mutates (Counter.count, Counter.myThing)
    let myCount: Counter = Counter(10)
  }
}
```

**Comment by mrRachar** [comment]
_This issue was originally [matteobilardi/flint/#2](https://github.com/matteobilardi/flint/issues/2) and has been moved here for further discussion_

**Comment by SusanEisenbach** [comment]
There are two things you can do now and we should discuss which of these you do when.

1) You set the use of the verifier to false so that you can do the move translation and the tools installation. The hope is that you have time at the end to go back and fix the verifier (or in the worst case scenario you remove it from Flint). Manshu should have a version that works with the verifier and she may just have to write your fixes.

2) You inject into the code (at the stage that it is handed to Boogie) the code that is needed (as if it had been written in the original source code). I don’t have a feeling for whether this is possible. It looks possible from the examples you sent. You could start with init.

On 29 Jul 2019, at 10:52, mrRachar <notifications@github.com<mailto:notifications@github.com>> wrote:


Right now I cannot simply initialise a struct in any function, in a contracts initialiser, or in its declaration. This includes built in structs such as Wei. The verifier complains that to initialise these we'd need to declare the function mutating. This is strange as the idea behind mutates(...) is that it declares that the function mutates its struct, not just creates new values. This right now means that every single field of every single struct that is initialised, even if temporarily, not affecting the outer state at all needs to be listed in the mutates list, which can get out of hand easily. Also note, Wei.rawValue shouldn't be read as a change in state of the blockchain, instead it is a local change of the field inside the Wei struct, and this would be needed to be done for any struct.

Simple example

contract Wallet {
  let coin: Wei = Wei(0)
}

Wallet :: (any) {
  public init() {} // fix with: mutates (Wei.rawValue)
}

More sophisticated example

struct Counter {
  var count: Int
  var myThing: Int = 0

  public init(value: Int = 0) {
    self.count = 0
  }
}

contract Test {
  var counter: Counter
  var owner: Address
}

Test :: caller <- (any) {
  public init() { // fix with: mutates (Counter.count, Counter.myThing)
    self.counter = Counter(4)
    self.owner = caller
    self.counter = Counter(4)
  }

  public func myFunc() { // fix with: mutates (Counter.count, Counter.myThing)
    let myCount: Counter = Counter(10)
  }
}
