### ISSUE TITLE
verification problem when argument and global variable have the same name

### ISSUE THREAD

**Issue by wmanshu** [flintlang/flint#440]
```
func setP1(p1: Address)
  mutates (p1)
{
  self.p1 = p1
  ...
}
```

For this setP1function, the post condition should be `post(p1 == p1)`, in which the first p1 refers to self.p1 and the second one is the argument passed into the function. 

However, this post condition will always hold since `p1 == p1` is always true.

So, how can the verifier tell that the two 'p1's are different.

**Comment by matteobilardi** [comment]
I think you should be able to help the verifier disambiguate between the two just by setting the postcondition to be `post(self.p1 == p1)`

**Comment by wmanshu** [comment]
But p1 also means self. p1 I think?

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by matteobilardi** [comment]
In this case, they do not have the same meaning. Normally, you would be correct in saying that `self.p1` and `p1` are equivalent in that they are two different names for exactly the same contract property. However, since your function has an argument named `p1`, the meaning of `p1` inside the function gets changed to that of the `p1` function argument: the function argument `p1` shadows the outer variable contract property with the same name. For this reason, the only name that you are left with that still allows you to refer to the contract property `p1` is `self.p1`.
