### ISSUE TITLE
Problem with Init()

### ISSUE THREAD

**Issue by wmanshu** [flintlang/flint#455]
If I initialize this global variable `var bids : [Address : [Bid]]` using `self.bids = [:[]]`. I get this error:
```
Expected ']' in dictionary literal expression at line 33, column 19:
    self.bids = [:[]]
```

If I initialize it by`self.bids = [:]`, then error message says post condition not holds
Where Bid is a self-defined struct

**Comment by mrRachar** [comment]
Firstly, the syntax `[:[]]` doesn't really make any sense. I finally figured out what you were talking about with `self.bids = [:]`, and you're right, any contract or struct field equivalent to 
```swift
contract ExampleContract {
  var x: [Address: [ExampleStruct]] = [:]  // Also fails with `let`
}
```
currently fail a Boogie post-condition, that must be generated somewhere by the verification system. I am having a look into this problem now.

It would be more helpful in the future to provide _simplified but implicitly complete_ examples of issues rather than your code to help diagnose them. For example, `self.bids` is completely out of context, etc.
